#!/bin/bash
#SBATCH --job-name=CHiCAGO_pipeline_NUTWT_recalibrated
#SBATCH --workdir=/gpfs/projects/bsc08/bsc08471/p53/Step2_CHiCAGO/downsampled/NUTWT_recalibration/
#SBATCH --error=/gpfs/projects/bsc08/bsc08471/p53/Step2_CHiCAGO/downsampled/NUTWT_recalibration/logs/CHiCAGO_pipeline_NUTWT_recalibrated_%j.err
#SBATCH --output=/gpfs/projects/bsc08/bsc08471/p53/Step2_CHiCAGO/downsampled/NUTWT_recalibration/logs/CHiCAGO_pipeline_NUTWT_recalibrated_%j.out
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=16
#SBATCH --time=02:00:00
#SBATCH --qos=debug
#SBATCH --constraint=highmem
/apps/GREASY/latest/INTEL/IMPI/bin/greasy /gpfs/projects/bsc08/bsc08471/p53/Step2_CHiCAGO/downsampled/NUTWT_recalibration/CHiCAGO_pipeline_NUTWT_recalibrated.cmd
