#!/bin/bash
#SBATCH --job-name=downsampled
#SBATCH --workdir=.
#SBATCH --error=logs/downsampled_%j.err
#SBATCH --output=logs/downsampled_%j.out
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=02:00:00
#SBATCH --qos=debug
#SBATCH --constraint=highmem
#SBATCH --mail-type=all
#SBATCH --mail-user=monica.cabrera@bsc.es
module load samtools
/apps/GREASY/latest/INTEL/IMPI/bin/greasy downsampled.cmd
