#!/bin/bash
#SBATCH --job-name=CHiCAGO_merge
#SBATCH --workdir=/gpfs/projects/bsc08/bsc08471/p53/Step2_CHiCAGO/downsampled/NUTWT_recalibration/
#SBATCH --error=/gpfs/projects/bsc08/bsc08471/p53/Step2_CHiCAGO/downsampled/NUTWT_recalibration/logs/CHiCAGO_merge_%j.err
#SBATCH --output=/gpfs/projects/bsc08/bsc08471/p53/Step2_CHiCAGO/downsampled/NUTWT_recalibration/logs/CHiCAGO_merge_%j.out
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=8
#SBATCH --time=02:00:00
#SBATCH --qos=debug
#SBATCH --constraint=highmem
/apps/GREASY/latest/INTEL/IMPI/bin/greasy /gpfs/projects/bsc08/bsc08471/p53/Step2_CHiCAGO/downsampled/NUTWT_recalibration/CHiCAGO_merge.cmd
