---
title: "HiC_Compartments_SupplFig1 "
output:
  pdf_document: default
  date: "`r format(Sys.time(), '%d %B, %Y')`"
  author: "Mónica Cabrera-Pasadas"
  html_document:
    keep_md: yes
---

```{r setup-chunk, include=FALSE}
# wd <- "/home/monica/Desktop/MN/"
wd <- "/home/mcabrera/Desktop/MN/"
results <- paste0(wd,"p53/results/HCT116/figures/")
data <- paste0(wd,"p53/data/HCT116/HiC/")  #path where the clean files are
samples <- readRDS(paste0(data,"samples.rds"))

knitr::opts_chunk$set(dev = "pdf",
                      dpi = 300,
                      # echo = FALSE, #to print code or not
                      cache = TRUE,
                      root.dir = results)

packages <- c("ggfortify","dendextend","colormap","paletteer", "ggthemes","scico","reshape","ggplot2","GenomicRanges","hrbrthemes","dplyr","tidyverse","ComplexHeatmap","circlize","factoextra")
invisible(lapply(packages, library, character.only = TRUE))

colors_samples=c("#fde725ff", "#37b578ff","#21908dff","#31668dff","#43377fff","#440154ff") # scales::show_col(colormap(colormap = colormaps$viridis,nshades=7), labels = T)
color_A_B_Compartments=c("#881010","#23447f") #heatmaply::cool_warm(2) (alternatives: https://r-charts.com/es/paletas-colores/)
color_heatmap_compartments <- colorRamp2(breaks = c(-0.5,0,0.5), colors = c("#23447f", "snow1","#881010"))

order_compartment_categories <- c("A-A","B-A","A-B","B-B")
order_compartment_p53_categories <- c("A_no_p53-A_no_p53","A_p53-A_p53","B_no_p53-A_no_p53","B_p53-A_p53","A_no_p53-B_no_p53","A_p53-B_p53","B_no_p53-B_no_p53","B_p53-B_p53")
```

# SupplFig1 ----
```{r loading_HiC_Compartments_dataset}
load(paste0(data,"Compartments.RData"))
```

## SupplFig1C.Fraction of genome in A and B compartment of all time points. Y-axis match the temporal status of p53 activation.
```{r SupplFig1C_HiC_Compartments_AB_distribution}
table_AB <- data.frame(apply(data.frame(Compartments.gr)[- grep("NULL", Compartments.gr$combinations),grep("Category_", colnames(data.frame(Compartments.gr))),], 2, function(x) { table(x) })) #Counting how many positive (A compartment) and negative (B compartment) eigenvectors values are in my table
colnames(table_AB) <-  sub("Category_", "", colnames(table_AB))

head(table_AB)
# Nut.0h Nut.1h Nut.4h Nut.7h Nut.10h Nut.24h
# A  16025  16746  16500  16260   14888   15208
# B  11220  10499  10745  10985   12357   12037

table_AB$compartment <- rownames(table_AB)
table_AB$compartment <- factor(table_AB$compartment, levels=c("A","B"))

table_AB %>% melt(id.vars = "compartment") %>%
        mutate(variable=factor(variable,levels=unique(rev(variable))))%>%
        ggplot(aes(y = variable, x = value, fill = compartment)) +
          geom_col() +
          geom_text(aes(label = paste0(round(value/nrow(data.frame(Compartments.gr)[- grep("NULL", Compartments.gr$combinations),])*100,digits = 2),"% ","in ",compartment,"\n","n=",value)),color="white", position = position_stack(vjust = .5), size=2.5)+
          theme_classic()+
          theme(axis.text.y=element_text(size=rel(1), angle=0),
                axis.text.x=element_text(size=rel(1)))+
          scale_fill_manual(values=c(color_A_B_Compartments))+
        scale_x_continuous(breaks = seq(0, nrow(data.frame(Compartments.gr)), by = 5000), expand = c(0,0))+ 
        xlab("")+
        ylab("")+
  labs(title='A/B genome distribution of all samples',
       subtitle=paste0('n=',nrow(data.frame(Compartments.gr)[- grep("NULL", Compartments.gr$combinations),]), ' compartments')) +
  theme(plot.subtitle=element_text(size=8, face='italic', color='grey50'))+
    geom_vline(xintercept=table_AB$Category_Nut.0h[2], color="white")
```

## SupplFig1E.Hierachical clustering according to dynamic compartment
```{r SupplFig1E_HiC_Compartments_Hierachical_clustering}
# Perform hierarchical cluster analysis.
dend <- t(data.frame(Compartments.gr)[!grepl("NULL",Compartments.gr$combinations) & grepl("dynamic", Compartments.gr$state_Compartments),][,c(samples)]) %>%  
        dist(method = "euclidean") %>% hclust(method="ward.D2") %>% sort %>% as.dendrogram()

dend %>%
  set("branches_k_color", value = c("#23447f","#881010"),k=2) %>%
  set("labels_col", value = c("#fde725ff","#43377fff","#440154ff","#37b578ff","#21908dff","#31668dff"), k = 6) %>%
  plot(horiz=FALSE, axes=TRUE, main="Hierarchical cluster of all the compartment with values in all samples")

```

## SupplFig1F.Heatmap of the non dynamic compartments 
```{r SupplFig1F_HiC_Compartments_Heatmap_no_dynamic_compartments}
Heatmap(as.matrix(data.frame(Compartments.gr)[!grepl("NULL",Compartments.gr$combinations) & !grepl("dynamic", Compartments.gr$state_Compartments),][,c(samples)]),column_title = "Basic heatmap of all regions with y axis according to genomic position",column_title_gp = gpar(fontsize = 5, fontface = "bold"),cluster_rows = T, show_row_names = F,cluster_columns=F,col = color_heatmap_compartments)
```
