#!/bin/bash
#SBATCH --job-name=HiCUP
#SBATCH --workdir=.
#SBATCH --error=logs/HiCUP_%j.err
#SBATCH --output=logs/HiCUP_%j.out
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=15:00:00
#SBATCH --constraint=highmem
#SBATCH --mail-type=all
#SBATCH --mail-user=monica.cabrera@bsc.es
module load bowtie2
module load bowtie
module load hicup
module load samtools
/apps/GREASY/latest/INTEL/IMPI/bin/greasy /gpfs/projects/bsc08/bsc08471/PCHiC/p53/HiCUP/HiCUP.cmd
